//window.API_BASIC = "/api/contest/basic";
//window.API_USERINFO = "/api/contest/userinfo";
//window.API_QUICKNAV = "/api/contest/quicknav";
//window.API_PROBLEMS = "/api/contest/problems";
//window.API_SUBMISSIONS_ADMIN = "/api/contest/admin/submissions"; // Exemplo endpoint
//window.API_REJUDGE = "/api/contest/admin/rejudge";              // Exemplo endpoint para rejulgamento
//window.API_SOURCE = "/api/open_training/submission_source";
//window.API_LOG = "/api/open_training/submission_log";
//window.TOKEN_KEY = "contest_token";

window.API_BASIC = "../basic.json";
window.API_USERINFO = "../userinfo.json";
window.API_QUICKNAV = "../quicknav.json";
window.API_PROBLEMS = "../problems.json";
window.API_SUBMISSIONS_ADMIN = "history-full.txt"; // Exemplo endpoint
window.API_REJUDGE = "/api/contest/admin/rejudge";              // Exemplo endpoint para rejulgamento
window.API_SOURCE = "/api/open_training/submission_source";
window.API_LOG = "history-full.txt";
window.TOKEN_KEY = "contest_token";
